### ISSUE TITLE
无法打TAG (Max retries exceeded with url）

### ISSUE THREAD

**Issue by wubushanyan** [NobeKanai/dvtag#6]
本地使用V2ray全局代理，chrome可以访问dlsite，之前还是正常的，今天对本地19个音声批量wav 转flac并打tag，出现了这个问题

尝试过关掉代理，就会得到以下错误
`2022-08-17 Wed 15:45:10 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B4194B3D00>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。')': /maniax/product/info/ajax?product_id=RJ393180`

大佬带带我，为啥会有这个问题

**环境**
```
Python 3.9.7
pip 22.2.2 
dvtag 0.4.4
requests 2.28.1
pyOpenSSL 22.0.0
```

**错误代码**
```
dvtag -w2f ./

2022-08-17 Wed 15:31:06 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /maniax/product/info/ajax?product_id=RJ393180
2022-08-17 Wed 15:31:06 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /maniax/product/info/ajax?product_id=RJ393180
2022-08-17 Wed 15:31:06 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /maniax/product/info/ajax?product_id=RJ393180
2022-08-17 Wed 15:31:06 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /maniax/product/info/ajax?product_id=RJ393180
2022-08-17 Wed 15:31:06 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))': /maniax/product/info/ajax?product_id=RJ393180
Traceback (most recent call last):
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.dlsite.com', port=443): Max retries exceeded with url: /maniax/product/info/ajax?product_id=RJ393180 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\Scripts\dvtag.exe\__main__.py", line 7, in <module>
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\main.py", line 41, in main
    start(path, args.w2f, args.w2m)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\main.py", line 25, in start
    start(file, w2f, w2m)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\main.py", line 19, in start
    tag(dirpath)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\dvtag\dvtag.py", line 71, in tag
    dv = DoujinVoice(rjid)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\dvtag\doujinvoice.py", line 23, in __init__
    self._init_metadata()
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\dvtag\doujinvoice.py", line 55, in _init_metadata
    rsp = session.get("https://www.dlsite.com/maniax/product/info/ajax?product_id=" + self.rjid)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\qq287\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.dlsite.com', port=443): Max retries exceeded with url: /maniax/product/info/ajax?product_id=RJ393180 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
```

**Comment by NobeKanai** [comment]
用 proxifier 之类的工具开全局代理可能出现这个问题， 可以尝试关闭全局代理然后在执行dvtag 命令前先设置代理相关的环境变量。 例如

```
set HTTP_PROXY=http://localhost:7890
set HTTPS_PROXY=http://localhost:7890
dvtag -w2f /path/to/library
```

或者使用其他的全局代理工具比如 [Netch](https://github.com/NetchX/Netch/)

**Comment by wubushanyan** [comment]
我使用Clash for Windows里面自带的CMD代理，没有错误了 感谢指点
